### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by esponapule** [wysiib/linter-languagetool#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Debian GNU/Linux
**Thrown From**: [linter-languagetool](https://github.com/wysiib/linter-languagetool) package 0.4.0

### Stack Trace

Uncaught SyntaxError: Unexpected token < in JSON at position 0

```
At file:///usr/share/atom/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at /packages/linter-languagetool/lib/linter-provider.coffee:65:29)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:26.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -0:58.7.0 intentions:highlight (input.hidden-input)
     -0:58.2.0 find-and-replace:show (input.hidden-input)
  2x -0:32.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.18 
atom-css-comb 3.1.0 
atom-htmltidy 5.1.0 
atom-prettify 0.1.3 
atom-python-run 0.7.3 
atom-toolbar 0.1.6 
auto-detect-indentation 1.3.0 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete-python 1.8.63 
bracket-close-jump 0.1.2 
busy-signal 1.3.0 
case-switch 2.2.4 
change-case 0.6.5 
close-tags 0.6.0 
color-picker 2.2.5 
drag-drop-text 0.1.4 
file-icons 2.1.2 
flex-tool-bar 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-markdown 0.20.0 
lines 0.13.1 
linkify 0.11.0 
linter 2.1.2 
linter-languagetool 0.4.0 
linter-php 1.3.2 
linter-python 3.1.1 
linter-spell-html 0.6.2 
linter-ui-default 1.2.2 
markdown-assistant 0.2.0 
markdown-helpers 0.3.0 
markdown-pdf 1.5.0 
markdown-preview-enhanced 0.10.12 
markdown-preview-plus 2.4.9 
markdown-themeable-pdf 1.2.0 
markdown-toc 0.4.2 
markdown-toolbar 0.1.2 
markdown-writer 2.6.4 
minimap 4.27.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
open-in-browser 0.5.0 
open-recent 5.0.0 
pandoc-convert 1.1.0 
php-cs-fixer 4.1.0 
pigments 0.39.1 
pretty-json 1.6.3 
print-code 0.6.0 
python-debugger 0.2.0 
python-indent 1.0.2 
python-tools 0.6.9 
simple-drag-drop-text 0.3.4 
smart-quotes-plus 2.1.0 
smarter-delete-line 1.1.2 
spell-check-project 0.7.0 
tag 0.4.0 
text-manipulation 0.6.0 
tidy-markdown 3.0.1 
title-case 0.4.0 
tool-bar 1.1.0 
tool-bar-config 0.1.0 
tool-bar-main 0.0.10 
tool-bar-markdown-writer 0.2.0 
toolbar-iconshortcuts 3.10.0 
trailing-spaces 0.4.0 
url-utils 0.2.1 
wordcount 2.10.4 
```

**Comment by wysiib** [comment]
I can reproduce the issue. At least on my device it stopped working with the update to language tool 3.6. Have to further investigate what is going wrong.

**Comment by wysiib** [comment]
Should be fixed with the latest release. I tested it using language tool 3.6.
